name: InvitePlayer
version: '1.0-SNAPSHOT'
main: org.aplugin.invitePlayer.InvitePlayer
api-version: '1.21'
author: 아포칼립스
website: https://discord.com/invite/2SSUvcx4vH
commands:
  invP:
    description: 플레이어 초대권 지급명령어
  cinvP:
    description: 콘솔 전용 명령어
permissions:
  invp.*:
    children:
      - invp.use
      - invp.cmds
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.0.0